package com.intellij.core.enums;

public enum ResponseCode {

    INTERNAL_ERROR,
    ACCESS_DENIED,
    USER_NOT_FOUND,
    NOTIFICATION_MARKED_AS_SEEN,
    USER_ALREADY_EXIST,
    DUPLICATE_EMAIL_EXIST,
    BAD_REQUEST,
    NOT_FOUND,
    CREATED,
    SERVICE_UNAVAILABLE,
    UNAUTHORIZED,

    DB_ERROR,
    IAM_ERROR,
    AWS_ERROR,

    ENTITY,
    OK,
    UPDATED,
    UNSUPPORTED_MEDIA_TYPE,
    GONE,
    INVALID_TEMPLATE_TYPE,
    WEBHOOK_SUCCESSFUL
}
