server:
  port: 8087

spring:
  main:
    web-application-type: reactive
  application:
    name: CloudApiGatewayApplication

  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://user-service}
          predicates:
            - Path=/api/user/**
          filters:
            - name: KubernetesToken
        - id: master-service
          uri: ${MASTER_SERVICE_URL:http://master-service}
          predicates:
            - Path=/api/master/**
          filters:
            - name: KubernetesToken

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: DEBUG
