server:
  port: 8761

spring:
  application:
    name: DiscoveryHealthDiscoveryApplication

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

management:
  endpoints:
    web:
      exposure:
        include: '*'