apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-service
  template:
    metadata:
      labels:
        app: master-service
    spec:
      containers:
        - name: master-service
          image: master-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SPRING_CLOUD_DISCOVERY_ENABLED
              value: "false"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "none"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:h2:mem:testdb"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.h2.Driver" 