apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  routes.yaml: |
    spring:
      cloud:
        gateway:
          routes:
            - id: user-service
              uri: ${USER_SERVICE_URL:http://user-service.default.svc.cluster.local:8081}
              predicates:
                - Path=/api/user/**
              filters:
                - name: KubernetesToken
            - id: master-service
              uri: ${MASTER_SERVICE_URL:http://master-service.default.svc.cluster.local:8082}
              predicates:
                - Path=/api/master/**
              filters:
                - name: KubernetesToken
