apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  routes.yaml: |
    spring:
      cloud:
        gateway:
          routes:
            - id: user-service
              uri: http://user-service
              predicates:
                - Path=/api/user/**
              filters:
                - name: KubernetesToken
            - id: master-service
              uri: http://master-service
              predicates:
                - Path=/api/master/**
              filters:
                - name: KubernetesToken
